namespace :db do
  desc "Check if specified emails exist in the database and output missing ones"
  task check_emails_exist: :environment do
    emails_to_check = %w[
    maud.miribel@edubga.com
Antonio.Schneider@edubga.com
caio.borba@edubga.com
Nahid.Salimi@edubga.com
Goncalo.Velez@edubga.com
Kairu.Yasuda@edubga.com
Yuri.Pinto@edubga.com
Tomas.Mancellos@edubga.com
bernadette.cooper@edubga.com
karim.ghanem@edubga.com
Tiago.Uys@edubga.com
Jacob.Paiva@edubga.com
Paulo.Abreu@edubga.com
drian.pool@edubga.com
Franco.Toit@edubga.com
Laura.Almeida@edubga.com
keandro.cunha@edubga.com
Sammy.Jefwa@edubga.com
Dario.Sousa@edubga.com
Regina.semana@edubga.com
Cynthia.Kaltschmidt@edubga.com
Theana.Figenschou@edubga.com
samantha.pires@edubga.com
angel.mburuu@edubga.com
Belen.Garcia@edubga.com
matthew.neves@edubga.com
diogo.ribeiro@edubga.com
Matilde.Santos@edubga.com
larisa.tremezano@edubga.com
Julya.Myrrha@edubga.com
Matthew.Owen@edubga.com
Kian.Pinto@edubga.com
lam.pong@edubga.com
jaroslav.slyusar@edubga.com
nina.teixeira@edubga.com
Nina.Gouveia@edubga.com
Robert.Baya@edubga.com
Zion.Nakasujja@edubga.com
Shukrani.Kitsao@edubga.com
lucciana.fonseca@edubga.com
aldiyar.issin@edubga.com
alina.issina@edubga.com
cedric.velde@edubga.com
Daphne.Deglon@edubga.com
soar-ide.dolan@edubga.com
sergio.araujo@edubga.com
jordy.pira@edubga.com
Chey.Farndell@edubga.com
chanel.helena@edubga.com
Amelie.Taeymans@edubga.com
Gustavo.Borba@edubga.com
Miguel.Magalhaes@edubga.com
ines.marinho@edubga.com
gerhardus.dutoit@edubga.com
dylan.reichman@edubga.com
Julio.bartolo@edubga.com
Caden.melvin@edubga.com
Antonio.Granger@edubga.com
malik.joaquim@edubga.com
Tiano.Prista@edubga.com
gabriela.guimaraes@edubga.com
leonardo.raposo@edubga.com
suelly.magaia@edubga.com
Shiri.Voll@edubga.com
Mariana.Clubley@edubga.com
Elisa.Barre@edubga.com
luchia.charles@edubga.com
Christine.Eyk@edubga.com
Akos.Wiandt@edubga.com
Maksymilian.Juzwuk@edubga.com
Nassim.Jebari@edubga.com
Marie.Scott@edubga.com
Maya.Sorensen@edubga.com
Fabiano.Rusu@edubga.com
zachary.booth@edubga.com
Jordan.Davids@edubga.com
Luney.Bronkhorst@edubga.com
Malcolm.Masule@edubga.com
jandjee.katjitae@edubga.com
sara.geraldes@edubga.com
Joel.Hansson@edubga.com
Samuel.Cerne@edubga.com
Matias.Almeida@edubga.com
Caetano.Correia@edubga.com
Mikayla.Sa@edubga.com
manuel.moreira@edubga.com
Guru.Manaise@edubga.com
Gaurav.Ganure@edubga.com
Michaela.Murdoch@edubga.com
Catarina.Weitzmann@edubga.com
nicole.ferreira@edubga.com
Jordan.Verrett@edubga.com
alexa.fourie@edubga.com
Arran.Guthrie-Strachan@edubga.com
Caleb.Uitenbroek@edubga.com
Darlene.Kamau@edubga.com
cristian.velde@edubga.com
choying.pelmo@edubga.com
Sonoma.Rushing@edubga.com
Lachlan.Gibson@edubga.com
Noah.Sweeney@edubga.com
Catharina.Boer@edubga.com
Georgia.MacDonald@edubga.com
Robert.MacDonald@edubga.com
Rebecca.Hewitt@edubga.com
senne.decock@edubga.com
kai.doughty@edubga.com
Madeline.Mandarino@edubga.com
claire.cannon@edubga.com
Kieran.Mercurio@edubga.com
carter.pearce@edubga.com
Maria.Alenikova@edubga.com
Gia.Pena@edubga.com
Eliot.Somers@edubga.com
Eric.Spalt@edubga.com
Myles.Detloff@edubga.com
Annemarie.Bentzel@edubga.com
Juliette.Bentzel@edubga.com
Cassidy.Olliff@edubga.com
riley.sweeting@edubga.com
chloe.borda@edubga.com
rocco.vanrumpt@edubga.com
vladimir.chiscop@edubga.com
olivia.swartz@edubga.com
dieter.roux@edubga.com
Theodore.Koenen@edubga.com
Fernando.Dutra@edubga.com
Pedro.Pires@edubga.com
Beatriz.magalhaes@edubga.com
cristiano.cruz@edubga.com
Yaroslav.Kiselev@edubga.com
Eziah.Callahan@edubga.com
fred.wong@edubga.com
Mali.Almeida@edubga.com
rita.lopes@edubga.com
gabriel.noah@edubga.com
Filipe.Teixeira@edubga.com
matilde.roff@edubga.com
Tayra.Ying@edubga.com
armando.mavhunga@edubga.com
ryan.godinho@edubga.com
valentino.santos@edubga.com
Nelson.Lambert@edubga.com
Georg.Oiesvold@edubga.com
Martin.Robinson@edubga.com
Zara.Caleca@edubga.com
Daniel.Hrab@edubga.com
Youri.Burghouwt@edubga.com
tae.cho@edubga.com
tasneen.satar@edubga.com
jake.acutt@edubga.com
olivia.freitas@edubga.com
issam.badour@edubga.com
Anna.Cowan-Allen@edubga.com
Alexandra.Saem@edubga.com
Ethan.Sinden@edubga.com
Riquelme.Cloete@edubga.com
keirnan.miller@edubga.com
Lena.Stern@edubga.com
Amanda.Garcia@edubga.com
Tanita.Strydom@edubga.com
zana.chontos@edubga.com
Jamie.Huber@edubga.com
Hare.Natori@edubga.com
Matilde.Silva@edubga.com
Roos.Knops@edubga.com
Juliette.Gerus@edubga.com
Dominique.Gerus@edubga.com
Kai.Sanchidrian@edubga.com
Adam.Ziv@edubga.com
Igor.Fioratti@edubga.com
Salvador.Buccimazza@edubga.com
Eileen.Watanabe@edubga.com
Francisca.Freitas@edubga.com
giovanni.morais@edubga.com
Leonor.Garnel@edubga.com
Chimu.Yasuda@edubga.com
Cooper.Lucas@edubga.com
gianluca.ariu@edubga.com
Albert.Dreijer@edubga.com
Akari.Roggio@edubga.com
Mees.Rodenburg@edubga.com
david.sicko@edubga.com
Nayana.Avellar@edubga.com
Finlay.Low@edubga.com
Matthew.Roux@edubga.com
riley.oneil@edubga.com
ashton.howie@edubga.com
Elijah.Buffington@edubga.com
Isabella.Boer@edubga.com
Jake.Lloyd@edubga.com
Reef.Sweeney@edubga.com
Julian.Klatt@edubga.com
Peter.Schmidt@edubga.com
Maxine.Manning@edubga.com
Alaynna.Malde@edubga.com
Lilli.Kohler@edubga.com
joas.vdwees@edubga.com
Albert.Giles@edubga.com
August.Collert@edubga.com
Alice.Sousa@edubga.com
gabriel.vieira@edubga.com
Vasco.Santo@edubga.com
martim.almeida@edubga.com
Benjamin.Briggs@edubga.com
Lila.Reynolds@edubga.com
Isabella.Robinson@edubga.com
mia.gouveia@edubga.com
tanisha.hillegonda@edubga.com
santino.delreal@edubga.com
quinn.alblas@edubga.com
oscar.connor@edubga.com
Saraphina.Tsang@edubga.com
Gabriella.Brits@edubga.com
henrique.abrunhosa@edubga.com
artur.abrunhosa@edubga.com
mateus.sa@edubga.com
Andre.Mendes@edubga.com
Pedro.Hipolito@edubga.com
Emilia.Koletic@edubga.com
Linnea.Ohman@edubga.com
Francisco.Almeida@edubga.com
Almog.Shuhami@edubga.com
Vasco.Abuabara@edubga.com
Jaime.Veselko@edubga.com
curtis.ho@edubga.com
michael.kochavi@edubga.com
Tiago.bartolo@edubga.com
matias.moreira@edubga.com
Antonio.borges@edubga.com
mariana.rodrigues@edubga.com
Manuel.Granger@edubga.com
Joao.Nunes@edubga.com
Francisco.Sousa@edubga.com
gabriel.sirot@edubga.com
jamil.ghanem@edubga.com
Dalila.deAzevedoPintoMartins@edubga.com
Keniya.Cuanda@edubga.com
Gustavo.Antunes@edubga.com
Tajah.Oquisso@edubga.com
kayra.siddik@edubga.com
omar.amirali@edubga.com
Libi.Voll@edubga.com
morgan-rae.pretorius@edubga.com
antonio.carlos@edubga.com
mamad.satar@edubga.com
thando.nesic@edubga.com
aleksander.sielewicz@edubga.com
nia.lopez@edubga.com
zawady.chirrime@edubga.com
Amy.Snare@edubga.com
Kyle.Adams@edubga.com
chloe.perumal@edubga.com
Holly.Gerber@edubga.com
daniel.hulley@edubga.com
Kyle.Busse@edubga.com
Marta.Rusu@edubga.com
eunice.mendonca@edubga.com
Benee.Bezuidenhout@edubga.com
Abigail.Muteka@edubga.com
Sade.Fredericks@edubga.com
lloyd.jansen@edubga.com
ferchal.shikongo@edubga.com
Shandre.Saem@edubga.com
lauren.louw@edubga.com
keanan.louw@edubga.com
muhammed.lulat@edubga.com
Martim.Sousa@edubga.com
malakai.mcdermott@edubga.com
Noah.Cerne@edubga.com
Martim.Santos@edubga.com
Lucas.Wehle@edubga.com
abel.andrade@edubga.com
Gabriella.Murdoch@edubga.com
augustine.leblanc@edubga.com
Kingsley.Pearson@edubga.com
valentijn.gent@edubga.com
Francisco.Castro@edubga.com
adam.halsband@edubga.com
aiden.ward@edubga.com
Jessica.Griffith@edubga.com
Svea.Gottstein@edubga.com
asger.skov@edubga.com
mischa.keggie@edubga.com
anabella.acevedo@edubga.com
Miro.Hout@edubga.com
Digby.Giles@edubga.com
Maximus.Collert@edubga.com
rohan.hay@edubga.com
Camille.Rapin@edubga.com
mairead.mcguire@edubga.com
niamh.harty@edubga.com
kaia.borda@edubga.com
nathaniel.duhon@edubga.com
Hannah-Mai.Archer@edubga.com
Kruschenka.Toit@edubga.com
Tyla.Farndell@edubga.com
aryn.burdett@edubga.com
goncalo.silva@edubga.com
camila.oliveira@edubga.com
Joao.Maria@edubga.com
matilde.antunes@edubga.com
sebastiao.lopes@edubga.com
Ofek.Shuhami@edubga.com
Roland.Conrad@edubga.com
Isabel.Marques@edubga.com
Zoey.Weaver@edubga.com
moshe.harav@edubga.com
leonor.baltazar@edubga.com
hannah.seffar@edubga.com
astor.welters@edubga.com
Elwyn.harborne@edubga.com
juan.toit@edubga.com
Aaron.Laleye@edubga.com
Aiden.Collin@edubga.com
Maxime.Murphy@edubga.com
Alexa.Condo@edubga.com
Aria.Ying@edubga.com
Chiara.Astegiano@edubga.com
Matthew.Koczner@edubga.com
Ruhan.Carrilho@edubga.com
pedro.paiva@edubga.com
Harry.Turley@edubga.com
Howard.Oiesvold@edubga.com
riley.acutt@edubga.com
Noah.Schuller-Nel@edubga.com
robyn.barry@edubga.com
Mark.Wiandt@edubga.com
Narayan.Ayala@edubga.com
Binyamin.Katar@edubga.com
Martha.O'Grady@edubga.com
Vincent.Nguyen@edubga.com
Sofia.Galkina@edubga.com
paulina.balsiukeviciute@edubga.com
Loze.Majiedt@edubga.com
Munier.Brenner@edubga.com
elzeetta.job@edubga.com
martinha.sousa@edubga.com
Jose.Garcia@edubga.com
estel.pelenis@edubga.com
Sebastiano.Correia@edubga.com
Jarko.Kreuzeder@edubga.com
Liv.Knops@edubga.com
Mika.Jaspers@edubga.com
Dayana.Kulhavenia@edubga.com
Mia.Pires@edubga.com
Ella.Gilady@edubga.com
Nora.Sverdrup@edubga.com
lukas.ostergren@edubga.com
Pablo.Gistau@edubga.com
josep.correa@edubga.com
nahary.pereira@edubga.com
philip.seidel@edubga.com
Kaidee.cunha@edubga.com
Laiba.Faridi@edubga.com
Tania.venter@edubga.com
naomi.zonenberga@edubga.com
odrija.zonenberga@edubga.com
rotem.edry@edubga.com
Ilay.Ziv@edubga.com
samuel.fradin@edubga.com
Indiana.Sweeney@edubga.com
jora.wees@edubga.com
ivo.matczak@edubga.com
stefan.igorovitch@edubga.com
Jyoti.Langley@edubga.com
Ezra.Hout@edubga.com
Tabitha.Giles@edubga.com
Nickolas.Allanson@edubga.com
emily.verhoog@edubga.com
Ori.Tal@edubga.com
Alice.Sousa@edubga.com
Maximilian.Hong@edubga.com
Carl.Siebert@edubga.com
alfie.roper@edubga.com
alan.gouallier@edubga.com
Paul.Bievre@edubga.com
Isabella.Botha@edubga.com
chase.gruber@edubga.com
grant.stroud@edubga.com
elizabeth.dutoit@edubga.com
Ema.Nuno@edubga.com
david.silva.cardoso@edubga.com
tiago.jung@edubga.com
max.huljev@edubga.com
Carlota.Boubee@edubga.com
Guilherme.Ferreira@edubga.com
rodrigo.pola@edubga.com
vasco.letras@edubga.com
akari.suda@edubga.com
Amelia.Rodriguez@edubga.com
victoria.sirot@edubga.com
liah.lobo@edubga.com
vasco.roff@edubga.com
Zara.Halawi@edubga.com
gabriel.paiva@edubga.com
adi.kimhi@edubga.com
Leo.Morihain@edubga.com
Ethan.Pretorius@edubga.com
Niklas.Baveystock-Brandt@edubga.com
enrique.berton@edubga.com
marciano.freitas@edubga.com
Igor.Lutak@edubga.com
Naveen.Ayala@edubga.com
Lia.Sardo@edubga.com
Mortimer.Levinson@edubga.com
Sienna.Sardo@edubga.com
Shane.Adam@edubga.com
hilma.amalovu@edubga.com
jaehyun.kwon@edubga.com
Ilay.Daniel@edubga.com
alexandre.buccimazza@edubga.com
jasmin.grether@edubga.com
louie.dreijer@edubga.com
natan.sicko@edubga.com
hannah.schmidt@edubga.com
ruby.oneil@edubga.com
tamina.lange@edubga.com
malia.doughty@edubga.com
dionysha.eugenia@edubga.com
Lucia.Bluestone@edubga.com
alexander.reichl@edubga.com
tyler.jeans@edubga.com
luisa.jung@edubga.com
Jules.Morihain@edubga.com
Romi.Katar@edubga.com
darcy.perrin@edubga.com
Jace.Bezuidenhout@edubga.com
nathan.stevens@edubga.com
noga.kimhi@edubga.com
ori.kimhi@edubga.com
keily.meyer@edubga.com
francisco.moniz@edubga.com
adriaan.knoetze@edubga.com
moustafa.mohamed@edubga.com
halle.campbell@edubga.com
ashley.rwamba@edubga.com
anna.artemenko@edubga.com
ella.leverington@edubga.com
daniela.lubbe@edubga.com
tom.matsuda@edubga.com
tiago.dinis@edubga.com
bianca.miranda@edubga.com
nils.antonsson@edubga.com
uma.mangal@edubga.com
khensani.sambo@edubga.com
simone.venichand@edubga.com
lincoln.paiva@edubga.com
caua.falcao@edubga.com
isabela.barda@edubga.com
samara.vaz@edubga.com
blake.naidoo@edubga.com
oliver.koletic@edubga.com
andreea.das@edubga.com
niranjan.mangal@edubga.com
ema.ferreira@edubga.com
louie.pottes@edubga.com
elliot.sousa@edubga.com
ema.dogarel@edubga.com
daphne.gonda@edubga.com
keanu.santos@edubga.com
cristiano.cardim@edubga.com
guilherme.anjo@edubga.com
christian.pibworth@edubga.com
hanley.robinson@edubga.com
ryan.viviers@edubga.com
poppy.robinson@edubga.com
ingeborg.rosenkilde@edubga.com
marielle.nobrega@edubga.com
juana.jaramillo@edubga.com
alexander.clubley@edubga.com
gaia.valentim@edubga.com
denis.tsaregorodtsev@edubga.com
josiah.grobler@edubga.com
abigail.grobler@edubga.com
nina.grochowska@edubga.com
natan.grochowski@edubga.com
liska.dombrosk@edubga.com
jayden.silva@edubga.com
jascha.zijl@edubga.com
mia.wasserman@edubga.com
riale.groenewald@edubga.com
victor.poblet@edubga.com
alessandro.gerardi@edubga.com
santiago.lima@edubga.com
luana.lima@edubga.com
eva.lima@edubga.com
bernie.levene@edubga.com
anica.young@edubga.com
gustav.gilliland@edubga.com
leona.kleinemeier@edubga.com
sophie.gordon@edubga.com
dylan.palacios@edubga.com
nitiggya.singh@edubga.com
maria.matos@edubga.com
benicio.gama@edubga.com
logan.basson@edubga.com
brendin.prinsloo@edubga.com
damien.gautier@edubga.com
lucy.nepilly@edubga.com
jamie.nepilly@edubga.com
maisey.reynolds@edubga.com
lily.nepilly@edubga.com
elliot.bleyaert@edubga.com
nia.ruddick@edubga.com
francisco.rovetta@edubga.com
philip.prinsloo@edubga.com
joshua.quincey@edubga.com
santiago.franco@edubga.com
luca.scholz@edubga.com
szonja.wiedermann@edubga.com
doeme.wiedermann@edubga.com
antonio.akl@edubga.com
ana.souza@edubga.com
mikael.ponte@edubga.com
adam.theron@edubga.com
ivo.ortmann@edubga.com
issa.salihi@edubga.com
zakariya.salihi@edubga.com
winter.weiss@edubga.com
holland.peereboom@edubga.com
laura.batalha@edubga.com
suzanne.retief@edubga.com
sophia.noctor@edubga.com
joshua.paiva@edubga.com
olivia.thomas@edubga.com
amit.natowicz@edubga.com
liot.ousback@edubga.com
gabriel.thomas@edubga.com
kayla.smith@edubga.com
yoseph.castro@edubga.com
mazuri.milyoni@edubga.com
sophia.ellis@edubga.com
sophia.stratton@edubga.com
somto.eribenne@edubga.com
angeline.rusu@edubga.com
edward.plesea@edubga.com
chisom.eribenne@edubga.com
caetano.alves@edubga.com
matias.jawad@edubga.com
giulia.michelini@edubga.com
diana.dosmukhamedova@edubga.com
scarlet.wilgrove@edubga.com
rafael.nascimento@edubga.com
noah.lisboa@edubga.com
oliver.burkinshaw@edubga.com
hubert.levinson@edubga.com
chandler.conrad@edubga.com
luca.ribeiro@edubga.com
sophie.kremer@edubga.com
yarin.harari@edubga.com
esperanza.sutil@edubga.com
rileyrobinsonrmr@gmail.com
yaara.twizer@edubga.com
henrique.coelho@edubga.com
luana.ferreira@edubga.com
duarte.catarino@edubga.com
maud.miribel@edubga.com
gabrielle.oliveira@edubga.com
samantha.pires@edubga.com
belen.garcia@edubga.com
lucciana.fonseca@edubga.com
aldiyar.issin@edubga.com
alina.issina@edubga.com
cedric.velde@edubga.com
Daphne.Deglon@edubga.com
Nassim.Jebari@edubga.com
andrey.senchenkov@edubga.com
Luca.Dinis@edubga.com
Sol.Dikkenberg@edubga.com
Alara.Simsek@edubga.com
arran.hem@edubga.com
Caleb.Uitenbroek@edubga.com
cristian.velde@edubga.com
choying.pelmo@edubga.com
Sonoma.Rushing@edubga.com
Lachlan.Gibson@edubga.com
Noah.Sweeney@edubga.com
tara.boer@edubga.com
Georgia.MacDonald@edubga.com
Robert.MacDonald@edubga.com
Rebecca.Hewitt@edubga.com
senne.decock@edubga.com
Kiano.Silva@edubga.com
Sarah.Abuabara@edubga.com
David.Prior@edubga.com
Fernando.Wilson@edubga.com
Jade.Steyn@edubga.com
Joao.Campos@edubga.com
Keanu.Schwedt@edubga.com
Manuel.Jordao@edubga.com
mekhai.maharaj@edubga.com
Tiago.Nogueira@edubga.com
Sofia.Hernandez@edubga.com
Akari.Roggio@edubga.com
Mees.Rodenburg@edubga.com
david.sicko@edubga.com
Nayana.Avellar@edubga.com
Finlay.Low@edubga.com
Matthew.Roux@edubga.com
riley.oneil@edubga.com
ashton.howie@edubga.com
Isabella.Boer@edubga.com
Jake.Lloyd@edubga.com
Reef.Sweeney@edubga.com
Julian.Klatt@edubga.com
Peter.Schmidt@edubga.com
Damien.Dos.Santos@edubga.com
valentijn.gent@edubga.com
Francisco.Castro@edubga.com
adam.halsband@edubga.com
aiden.ward@edubga.com
Jessica.Griffith@edubga.com
Svea.Gottstein@edubga.com
asger.skov@edubga.com
mischa.keggie@edubga.com
anabella.acevedo@edubga.com
Elwyn.harborne@edubga.com
Mateus.Guimaraes@edubga.com
Michael.Aviv@edubga.com
Laiba.Faridi@edubga.com
tania.venter.bga@gmail.com
naomi.zonenberga@edubga.com
odrija.zonenberga@edubga.com
rotem.edry@edu.bga.com
Ilay.Ziv@edubga.com
samuel.fradin@edubga.com
Indiana.Sweeney@edubga.com
jora.wees@edubga.com
stefan.igorovitch@edubga.com
artem.senchenkov@edubga.com
natan.sicko@edubga.com
hannah.schmidt.bga@gmail.com
ruby.oneil@edubga.com
anna.artemenko@edubga.com
ella.leverington@edubga.com
bianca.miranda@edubga.com
veera.houldsworth@edubga.com
samir.karataev@edubga.com
seph.amzic@edubga.com
ashiana.gupta@edubga.com
ingeborg.rosenkilde@edubga.com
jayden.silva@edubga.com
santiago.franco@edubga.com
szonja.wiedermann@edubga.com
doeme.wiedermann@edubga.com
lily.brien@edubga.com
winterweiss@edubga.com
sophia.noctor@edubga.com
oliver.burkinshaw@edubga.com
Muhammad.Arham@edubga.com
paola.kempinsky@edubga.com
Norah.Blank@edubga.com
Aimee.Jones@edubga.com
Guila.Jones@edubga.com
Lucas.Saeger@edubga.com
Rafael.Santos@edubga.com
raquel.osbourne@edubga.com
emile.hevia@edubga.com
josephine.hevia@edubga.com
Ilya.Boldyrev@edubga.com
afonso.gomes@edubga.com
Wayra.Duran@edubga.com
Tatiana.Gouveia@edubga.com
Victoria.Montero@edubga.com
Boluwashefe.Odojukan@edubga.com
diego.kartoprawiro@edubga.com
Brandon.Harbison@edubga.com
Elisabeth.Laseur@edubga.com
Nadia.Li@edubga.com
cole.lehenbauer@edubga.com
emery.lehenbauer@edubga.com
Ada.Schiller@edubga.com
sarah.kassam@edubga.com
Sara.Krnic@edubga.com
Veronika.Struncena@edubga.com
Camila.Macedo@edubga.com
Juna.Bruns@edubga.com
Wilm.Bruns@edubga.com
Catarina.Lunekova@edubga.com
Marta.Frota@edubga.com
ryan.molnar@edubga.com
antonio.carvalho@edubga.com
xueting.ge@edubga.com
juliana.gomes@edubga.com
una.krickovic@edubga.com
eva.krolikowski@edubga.com
Naia.Lincoln@edubga.com
honey.chhantyal@edubga.com
yara.pinto@edubga.com
philip.ingutia@edubga.com
thomas.barnett@edubga.com
Joao.Breuer@edubga.com
odin.scholten@edubga.com
Mila.Mitchell@edubga.com
Avalina.Thompson@edubga.com
Isaac.Mannings@edubga.com
Hannah.Cataldo@edubga.com
Agam.dakon@edubga.com
or.dakon@edubga.com
ana.oliveira@edubga.com
Leah.Pun@edubga.com
Sienna.Pun@edubga.com
Declan.Lombardi@edubga.com
Salvador.Pinto@edubga.com
bexultan.nadir@edubga.com
christopher.justino@edubga.com
daniel.lu@edubga.com
Guan.Liming@edubga.com
jacopo.basso@edubga.com
Joao.Sa@edubga.com
Prince.Mangochi@edubga.com
snehil.yannam@edubga.com
tanakorn.johnsen@edubga.com
Tomas.Gureshidze@edubga.com
Tommaso.Drusian@edubga.com
ulrich.sharmin@edubga.com
wayan.ha@edubga.com
Elene.Dreher@edubga.com
Valerie.Dreher@edubga.com
Ines.Cruz@edubga.com
safa.mayami@edubga.com
iestyn.holloway@edubga.com
isabella.holloway@edubga.com
eugene.shibusawa@edubga.com
christian.Otenigbagbe@edubga.com
kaiden.soares@edubga.com
isabella.lisboa@edubga.com
ella.rihs@edubga.com
jane.velichko@edubga.com
mariia.gotovska@edubga.com
vasco.lopes@edubga.com
Manan.Dass@edubga.com
Mehek.Dass@edubga.com
Ugnius.Zukas@edubga.com
Tom.Masluk@edubga.com
Luca.Dinis@edubga.com
Antonina.Wos@edubga.com
Samuel.Woolston@edubga.com
alice.anacleto@edubga.com
francisca.barros@edubga.com
teresa.barbosa@edubga.com
Tiago.Nogueira@edubga.com
Jade.Steyn@edubga.com
Jordan.Steyn@edubga.com
mitchel.fourie@edubga.com
davyd.vysotskyi@edubga.com
gabriela.mekkaoui@edubga.com
giuseppe.basciu@edubga.com
fairouze.zandi@edubga.com
mahira.zandi@edubga.com
Alex.Siller@edubga.com
Francisco.Lopes@edubga.com
Brites.Macedo@edubga.com
Matilde.Gadyt@edubga.com
Samuel.Hernandez@edubga.com
Sofia.Hernandez@edubga.com
Oliver.Clinton@edubga.com
Stella.Clinton@edubga.com
Joao.Campos@edubga.com
Leonardo.Rodrigues@edubga.com
Laura.Piwowarczyk@edubga.com
Joshua.Smith@edubga.com
Lilian.Smith@edubga.com
Alara.Simsek@edubga.com
amanda.rombaut@edubga.com
James.Nuttall@edubga.com
farrah.browning@edubga.com
joana.saldanha@edubga.com
Chloe.Toppo@edubga.com
Yarden.Lidor@edubga.com
lior.zarchi@edubga.com
Gabrielle.Oliveira@edubga.com
Sophia.Lundin@edubga.com
Frauke.Vandenhoeck@edubga.com
Clara.Venegas@edubga.com
Kiano.Silva@edubga.com
Raquel.Alonso@edubga.com
Sofia.Alonso@edubga.com
Gabriela.Amorim@edubga.com
Mallory.Woodson@edubga.com
Bruno.Oliveira@edubga.com
Charlie.Dale@edubga.com
Ella.Nachtergaele@edubga.com
Sol.Dikkenberg@edubga.com
Diogo.Lima@edubga.com
seph.amzic@edubga.com
nikita.tambiev@edubga.com
andrey.senchenkov@edubga.com
artem.senchenkov@edubga.com
Sofia.Grekova@edubga.com
nikola.zonenberga@edubga.com
Gerian.Beest@edubga.com
Nicky.Beest@edubga.com
Gijs.Vries@edubga.com
max.emmerich@edubga.com
justus.emmerich@edubga.com
Fernando.Wilson@edubga.com
Elija.Abraham@edubga.com
Charlotte.Browning@edubga.com
Bixby.Browning@edubga.com
Goncalo.Almeida@edubga.com
afonso.sousa@edubga.com
Damien.Dos.Santos@edubga.com
David.Henriques@edubga.com
Kemeul.Meyer@edubga.com
Michael.McDermott@edubga.com
Nguyen.Duy@edubga.com
Lucy.Stroud@edubga.com
Felipe.Braga@edubga.com
ocean.larkey@edubga.com
Titus.Vieira@edubga.com
Elena.Vieira@edubga.com
lily.brien@edubga.com
Regan.Quinn@edubga.com
Caetana.Cardoso@edubga.com
Daniel.Deurhof@edubga.com
Antonio.Antunes@edubga.com
Mateus.Santos@edubga.com
Clara.Varvaroi@edubga.com
Gabriel.ComparadaCorreia@edubga.com
Sadwan.Ornob@edubga.com
Olivia.Chowgule@edubga.com
James.Foil@edubga.com
naomi.thomas@edubga.com
Michaela.Silva@edubga.com
michael.gutman@edubga.com
Maria.Cappello@edubga.com
illia.nesterov@edubga.com
Sofiia.Danylchenko@edubga.com
elena.varley@edubga.com
ashiana.gupta@edubga.com
richaad.jamal@edubga.com
Maya.Solomons@edubga.com
pavlos.ignatiou@edubga.com
edan.ehrlich@edubga.com
Mateus.Guimaraes@edubga.com
Ines.Fernandes@edubga.com
Michael.Aviv@edubga.com
yevhen.buriak@edubga.com
arthur.kouchnirenko@edubga.com
alex.cristovao@edubga.com
ikechukwu.oji@edubga.com
Sarah.Abuabara@edubga.com
mekhai.maharaj@edubga.com
Manuela.Martins@edubga.com
Lucas.Marques@edubga.com
Gaspar.Bonacho@edubga.com
Ilan.Flak@edubga.com
Yanna.Matheou@edubga.com
antonio.gomes@edubga.com
sebastian.matos@edubga.com
Sheikh.Ahmer@edubga.com
Keanu.Schwedt@edubga.com
Manuel.Jordao@edubga.com
eduardo.oliveira@edubga.com
avery.dacre@edubga.com
Sophia.StewartDacre@edubga.com
Rocco.Baldwin@edubga.com
veera.houldsworth@edubga.com
Chloe.Koenen@edubga.com
Laurin.Haefeli-Hestvik@edubga.com
S.Jamil@edubga.com
Manaka.Hada@edubga.com
samir.karataev@edubga.com
Filipe.Romba@edubga.com
alani.henriques@edubga.com
malik.henriques@edubga.com
matilde.santos@edubga.com
Antonio.Pereira@edubga.com
David.Prior@edubga.com
kayla.swardt@edubga.com
talya.yehuda@edubga.com
    ]
    puts "Checking #{emails_to_check.count} emails..."

    # Find missing emails
    missing_emails = emails_to_check.reject do |email|
      User.exists?(email: email.downcase)
    end

    # Output the result
    if missing_emails.any?
      puts "The following emails were not found in the database:"
      puts missing_emails
      puts "Total: #{missing_emails.count}"
    else
      puts "All emails are present in the database."
    end
  end
end
