services:
  db_test:
    image: postgres:14.2-alpine
    volumes:
      - ./databackup/data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - .env
    ports:
      - "5433:5432"
